"""
src/caption_module.py
──────────────────────
Handles image captioning using the fine-tuned BLIP model and enriches
raw captions with spatial context from YOLO detections.

Two main classes:
  SceneCaptioner        — Loads BLIP and generates raw captions
  SpatialReasoningNLP   — Combines BLIP output with YOLO detections
                          to produce rich, human-readable scene descriptions
"""

import time
import logging
from typing import List, Optional, Dict

import torch
from PIL import Image
import numpy as np

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))
from config import (
    DEVICE, USE_FP16, BLIP_PRETRAINED_NAME, BLIP_FINETUNED_PATH,
    BLIP_USE_FINETUNED, BLIP_MAX_NEW_TOKENS, BLIP_NUM_BEAMS,
    BLIP_CAPTION_INTERVAL,
)
from src.vision_module import DetectionList

log = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# SceneCaptioner
# ─────────────────────────────────────────────────────────────────────────────

class SceneCaptioner:
    """
    Loads the BLIP image captioning model (fine-tuned or pre-trained)
    and generates captions for input frames.

    Respects BLIP_CAPTION_INTERVAL to throttle inference calls —
    captioning runs every N seconds in the background.
    """

    def __init__(self):
        from transformers import BlipProcessor, BlipForConditionalGeneration

        if BLIP_USE_FINETUNED:
            model_path = str(Path(BLIP_FINETUNED_PATH) / "best")
            if not Path(model_path).exists():
                log.warning(
                    f"Fine-tuned BLIP not found at {model_path}. "
                    "Falling back to pre-trained weights."
                )
                model_path = BLIP_PRETRAINED_NAME
        else:
            model_path = BLIP_PRETRAINED_NAME

        log.info(f"Loading BLIP captioner from: {model_path}")
        self.processor = BlipProcessor.from_pretrained(model_path)
        self.model     = BlipForConditionalGeneration.from_pretrained(model_path)
        self.model.eval().to(DEVICE)

        self._last_caption_time = 0.0
        self._last_caption      = ""
        log.info("BLIP captioner loaded ✓")

    @torch.no_grad()
    def caption(self, frame: np.ndarray) -> Optional[str]:
        """
        Generates a caption for the given frame.
        Returns None if called before BLIP_CAPTION_INTERVAL has elapsed.
        """
        now = time.time()
        if now - self._last_caption_time < BLIP_CAPTION_INTERVAL:
            return None     # Too soon — skip

        image = Image.fromarray(cv2_to_pil(frame))
        inputs = self.processor(images=image, return_tensors="pt").to(DEVICE)

        with torch.cuda.amp.autocast(enabled=USE_FP16):
            ids = self.model.generate(
                **inputs,
                max_new_tokens=BLIP_MAX_NEW_TOKENS,
                num_beams=BLIP_NUM_BEAMS,
                early_stopping=True,
            )

        caption = self.processor.decode(ids[0], skip_special_tokens=True).strip()
        self._last_caption_time = now
        self._last_caption      = caption
        return caption

    @property
    def last_caption(self) -> str:
        return self._last_caption


def cv2_to_pil(frame: np.ndarray) -> np.ndarray:
    """Converts a BGR OpenCV frame to RGB numpy array for PIL."""
    return frame[:, :, ::-1]   # BGR → RGB


# ─────────────────────────────────────────────────────────────────────────────
# SpatialReasoningNLP
# ─────────────────────────────────────────────────────────────────────────────

# Priority objects that should always be mentioned first
PRIORITY_OBJECTS = {
    "person", "car", "truck", "bus", "motorcycle", "bicycle",
    "dog", "chair", "stairs", "step", "pole", "fire hydrant",
    "stop sign", "bench", "door",
}


class SpatialReasoningNLP:
    """
    Enriches a raw BLIP caption with spatial object information from YOLO
    to produce a complete, grammatically correct scene description.

    Output example:
        "You are in a living room. A chair is very close to your 9 o'clock.
         A person is nearby at your 12 o'clock."
    """

    def build_description(
        self,
        raw_caption: str,
        detections: DetectionList,
    ) -> str:
        """
        Combines BLIP caption + YOLO spatial detections into one sentence.

        Args:
            raw_caption:  Caption generated by BLIP (scene-level context).
            detections:   List of enriched detection dicts from ObjectDetector.

        Returns:
            Full descriptive sentence for the TTS engine.
        """
        parts: List[str] = []

        # 1. Scene-level context from BLIP
        if raw_caption:
            scene = raw_caption.rstrip(".")
            parts.append(f"You are looking at: {scene}.")

        # 2. Priority danger-zone objects first
        danger_items = [d for d in detections if d["in_danger_zone"]]
        if danger_items:
            top = danger_items[0]
            parts.append(
                f"Warning: {_article(top['label'])} {top['label']} is "
                f"{top['distance_word']}, {top['clock_pos']}."
            )

        # 3. Remaining top detections (up to 3, skip danger-zone duplicates)
        seen_labels = {d["label"] for d in danger_items}
        mentioned   = 0
        for det in detections:
            if mentioned >= 3:
                break
            if det["in_danger_zone"] or det["label"] in seen_labels:
                continue
            parts.append(
                f"{_article(det['label']).capitalize()} {det['label']} is "
                f"{det['distance_word']}, {det['clock_pos']}."
            )
            seen_labels.add(det["label"])
            mentioned += 1

        if not parts:
            return "The scene appears clear. No obstacles detected."

        return " ".join(parts)

    def build_danger_alert(self, detection: Dict) -> str:
        """
        Generates an urgent, short alert for a danger-zone object.
        Used for HIGH-priority TTS interrupts.
        """
        return (
            f"Caution! {_article(detection['label']).capitalize()} "
            f"{detection['label']} is {detection['distance_word']} "
            f"{detection['clock_pos']}!"
        )


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

_VOWELS = set("aeiouAEIOU")

def _article(word: str) -> str:
    """Returns 'an' if word starts with a vowel, else 'a'."""
    return "an" if word and word[0] in _VOWELS else "a"
